language: rust
cache: cargo
before_script:
- cargo install mdbook || true
addons:
  apt:
    packages:
    - libasound2-dev
rust:
- stable
script:
- mdbook build
- cd book-tests && cargo test -v
- cd ..
deploy:
  provider: script
  script: bash ./travis_deploy.sh
  on:
    branch: master
env:
  global:
  - secure: iGBT/EupxTg0jr14s2LKXWrmaYiIwRELLj4s7iiysRT6lGSqh8xKok7GMOcahQUig8N/rC7qlORs88Mr2qFNKGUL6kXTlU1IiAHUURpr+uiN3EoqTwmwr4UX7VVJLRjXF5j81AhfmXK7z7Q3QKqpHISsEIci0Q+joZQhnTZmBAJ/exwLs52Vnd/HyzKYjUiG3Bu4s+5iJ0TGU0GI4572LJzpldhabdts8vwVcZfqM1J0QHdLHIKJn3OXXxjllGD8TSycJALg9F6U7sHmOSp2tqHRkpZDsjL9c1PN4vxUi96PDbcO2o+8Uo9IAzbwc2QriabmhWiftd7fzZxjTky5l+EtA5/CTfLlJPnzNFfIpGnJOcvkVYU01v20AFd423gq5gFg0gqQCbr3GKmDF3mf3K3SmJ88PK615bSCgvC2f1QpnC6dSUXDSYYIPvNsed7KAgUsSWjUv3bbtYIiUy7hXt81Fi2b4Zhm/jkkLU9ltZ6IU9bFWWaR/uNXbGvndrYZfK27T7L0HfxfNyF3ovNjezGuUgC+1hirDvuwTLheQ4gqMwCRX6fyuOvhWHhPSJXFjuIwYVOaLYQpQOd4NVFD77588WTSczvEOlNGGpl4f3LAYI1eNRy2ilhu2bVtmppbJBCPC/FTjSPZD0tqr4x0737CWJgiAOtGBVn/e2nnF7Y=
