language: rust
before_script:
- rustup component add rustfmt

addons:
    apt:
        packages:
            - libasound2-dev
rust:
    - nightly
    - beta
    - stable

script:
    - cargo fmt --all -- --check
    - cargo build -v
    - cargo test -v
    - cargo doc -v
