language: rust
cache: cargo
before_script:
- rustup component add rustfmt
rust:
    - nightly
    - stable
script:
    - cargo fmt --all -- --check
    - cargo check --verbose
    - cargo test --verbose
    - cargo doc --verbose
