language: rust
cache: cargo

addons:
    apt:
        packages:
            - libasound2-dev
            - libxcb-composite0-dev

matrix:
    include:
        - name: "Test nightly"
          rust: nightly

        - name: "Test beta"
          rust: beta

        - name: "Test stable"
          rust: stable

        - name: "Validate doc"
          rust: stable
          before_script:
              - rustup component add rustfmt
          script:
              - cargo fmt --all -- --check
              - cargo doc --no-deps -v

script:
    - cargo build -v
    - cargo test -v
