[package]
name = "nannou_isf"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotglsl = { path = "../hotglsl" }
isf = { git = "https://github.com/nannou-org/isf", branch = "master" }
nannou = { git = "https://github.com/nannou-org/nannou", branch = "master" }
thiserror = "1"
