[workspace]
members = [
    "generative_design",
    "nannou",
    "nannou_audio",
    "nannou_isf",
    "nannou_laser",
    "nannou_new",
    "nannou_osc",
    "nannou_package",
    "nannou_timeline",
    "nature_of_code",
]
