[package]
name = "nannou"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A Creative Coding Framework for Rust."
readme = "README.md"
keywords = ["creative", "sketch", "graphics", "audio"]
license = "MIT"
repository = "https://github.com/MindBuffer/nannou.git"
homepage = "https://github.com/MindBuffer/nannou"

[dependencies]
cgmath = { version = "0.15", features = ["serde"] }
conrod = { version = "0.56", features = ["winit", "glium"] }
cpal = "0.5"
find_folder = "0.3"
glium = "0.18"
image = "0.16"
noise = "0.4"
palette = "0.2"
rand = "0.3"
rosc = "0.1"
sample = "0.7"
