[package]
name = "nannou_timeline"
version = "0.2.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A timeline widget, compatible with all conrod GUI projects."
readme = "README.md"
keywords = ["timeline", "automation", "GUI", "conrod", "envelope"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nannou-org/nannou_timeline.git"
homepage = "https://nannou.cc"

[features]
default = ["serde"]


[dependencies]
conrod_derive = "0.68"
conrod_core = "0.68"
envelope = "0.8"
itertools = "0.4.16"
num = "0.1.27"
pitch_calc = { version = "0.11", features = ["serde_serialization"] }
time_calc = { version= "0.13", features = ["serde"] }
serde = { version = "1.0.*", features = ["derive"], optional = true }


[dev-dependencies]
nannou = "0.12"
rand = "0.3.12"
serde_json = "1.0"