[package]
name = "nannou"
version = "0.13.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A Creative Coding Framework for Rust."
readme = "README.md"
keywords = ["creative", "sketch", "graphics", "audio"]
license = "MIT"
repository = "https://github.com/nannou-org/nannou.git"
homepage = "https://github.com/nannou-org/nannou"
edition = "2018"

[features]
default = ["notosans"]

[dependencies]
cgmath = { version = "0.17", features = ["serde"] }
conrod_core = "0.69"
conrod_wgpu = "0.69"
conrod_winit = "0.69"
daggy = "0.6"
find_folder = "0.3"
image = "0.23"
lyon = "0.15"
noise = "0.6"
notosans = { version = "0.1", optional = true }
palette = "0.5"
pennereq = "0.3"
rand = { version = "0.7", features = ["small_rng"] }
rusttype = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
threadpool = "1"
toml = "0.5"
walkdir = "2"
wgpu = "0.4"
winit = "0.22"

[dev-dependencies]
audrey = "0.2"
futures = "0.3"
nannou_audio = "0.2"
nannou_laser = "0.3"
nannou_osc = "0.1"

# --------------- Nannou Examples
[[example]]
name = "all_functions"
path = "examples/all_functions.rs"
[[example]]
name = "capture_hi_res"
path = "examples/capture_hi_res.rs"
[[example]]
name = "loop_mode"
path = "examples/loop_mode.rs"
[[example]]
name = "multi_window"
path = "examples/multi_window.rs"
[[example]]
name = "named_color_reference"
path = "examples/named_color_reference.rs"
[[example]]
name = "osc_receiver"
path = "examples/osc_receiver.rs"
[[example]]
name = "osc_sender"
path = "examples/osc_sender.rs"
[[example]]
name = "simple_audio"
path = "examples/simple_audio.rs"
[[example]]
name = "simple_audio_file"
path = "examples/simple_audio_file.rs"
[[example]]
name = "simple_capture"
path = "examples/simple_capture.rs"
[[example]]
name = "simple_ui"
path = "examples/simple_ui.rs"
[[example]]
name = "simple_window"
path = "examples/simple_window.rs"
[[example]]
name = "simple_loop"
path = "examples/simple_loop.rs"
[[example]]
name = "template_app"
path = "examples/template_app.rs"
[[example]]
name = "template_sketch"
path = "examples/template_sketch.rs"

# --------------- Examples Basics
[[example]]
name = "1_nannou_events"
path = "examples/basics/1_nannou_events.rs"
[[example]]
name = "2_variables_window_console"
path = "examples/basics/2_variables_window_console.rs"
[[example]]
name = "3_variable_scope"
path = "examples/basics/3_variable_scope.rs"
[[example]]
name = "4_conditionals"
path = "examples/basics/4_conditionals.rs"
[[example]]
name = "5_loops"
path = "examples/basics/5_loops.rs"
[[example]]
name = "6_functions"
path = "examples/basics/6_functions.rs"
[[example]]
name = "7_modules"
path = "examples/basics/7_modules/7_modules.rs"

# --------------- Draw Examples
[[example]]
name = "draw"
path = "examples/draw/draw.rs"
[[example]]
name = "draw_blend"
path = "examples/draw/draw_blend.rs"
[[example]]
name = "draw_mesh"
path = "examples/draw/draw_mesh.rs"
[[example]]
name = "draw_polygon"
path = "examples/draw/draw_polygon.rs"
[[example]]
name = "draw_polyline"
path = "examples/draw/draw_polyline.rs"
[[example]]
name = "draw_text"
path = "examples/draw/draw_text.rs"
[[example]]
name = "draw_text_path"
path = "examples/draw/draw_text_path.rs"
[[example]]
name = "draw_texture"
path = "examples/draw/draw_texture.rs"
[[example]]
name = "draw_texture_sampler"
path = "examples/draw/draw_texture_sampler.rs"
[[example]]
name = "draw_textured_mesh"
path = "examples/draw/draw_textured_mesh.rs"
[[example]]
name = "draw_textured_path"
path = "examples/draw/draw_textured_path.rs"
[[example]]
name = "draw_textured_polygon"
path = "examples/draw/draw_textured_polygon.rs"
[[example]]
name = "draw_transform"
path = "examples/draw/draw_transform.rs"

# --------------- WGPU Examples
[[example]]
name = "wgpu_compute_shader"
path = "examples/wgpu/wgpu_compute_shader/wgpu_compute_shader.rs"
[[example]]
name = "wgpu_image"
path = "examples/wgpu/wgpu_image/wgpu_image.rs"
[[example]]
name = "wgpu_image_sequence"
path = "examples/wgpu/wgpu_image_sequence/wgpu_image_sequence.rs"
[[example]]
name = "wgpu_teapot"
path = "examples/wgpu/wgpu_teapot/wgpu_teapot.rs"
[[example]]
name = "wgpu_teapot_camera"
path = "examples/wgpu/wgpu_teapot_camera/wgpu_teapot_camera.rs"
[[example]]
name = "wgpu_triangle"
path = "examples/wgpu/wgpu_triangle/wgpu_triangle.rs"
[[example]]
name = "wgpu_triangle_raw_frame"
path = "examples/wgpu/wgpu_triangle_raw_frame/wgpu_triangle_raw_frame.rs"

# --------------- Laser
[[example]]
name = "laser_frame_stream"
path = "examples/laser/laser_frame_stream.rs"
[[example]]
name = "laser_frame_stream_gui"
path = "examples/laser/laser_frame_stream_gui.rs"
[[example]]
name = "laser_raw_stream"
path = "examples/laser/laser_raw_stream.rs"

# --------------- Offline examples
[[example]]
name = "offline_01"
path = "examples/offline/tree.rs"
