name: nannou

on: [push, pull_request]

jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  ubuntu-test-default-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install alsa dev tools
      run: sudo apt-get install libasound2-dev
    - name: Install libxcb dev tools
      run: sudo apt-get install libxcb-composite0-dev
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run default features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose

  ubuntu-test-all-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install alsa dev tools
      run: sudo apt-get install libasound2-dev
    - name: Install libxcb dev tools
      run: sudo apt-get install libxcb-composite0-dev
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run all features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --all-features --verbose
